language: node_js
node_js: 8.11.3
git:
  submodules: true
branches:
  only:
  - source
cache:
  directories:
  - node_modules
before_install:
- npm -g install npm@6.2.0
install:
- npm ci
script:
- 'echo "version: 2.3.0" >> ./themes/icarus/_config.yml'
- npm run hexo generate
- npm run hexo deploy
